services:
  pacman:
    build: .
    container_name: pacman
    ports:
      - "8080:8080"  # HOST:CONTAINER

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
