apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: default/my-splunk-otel-collector
    spec:
      containers:
        - name: pacman
          image: quay.io/pgattamaneni/pacman-app:latest
          env:
            - name: SPLUNK_OTEL_AGENT
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(SPLUNK_OTEL_AGENT):4318"
            - name: OTEL_SERVICE_NAME
              value: "pacman"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=production,service.version=0.0.1"
            - name: MONGO_SERVICE_HOST
              value: "104.196.11.24"
            - name: MONGO_VALIDATE_SSL
              value: "false"
          command:
            - node
            - -r
            - "@splunk/otel/instrument"
            - bin/server.js